### ISSUE TITLE
edX's version of this repo

### ISSUE THREAD

**Issue by tkeemon** [appsembler/edx-app-boilerplate#2]
Looks like edX is making cookiecutter versions of:
- IDAs: https://github.com/edx/cookiecutter-django-ida
- XBlocks: https://github.com/edx/cookiecutter-xblock
- Django Apps: https://github.com/edx/cookiecutter-django-app/

We should probably keep an eye on those and see what we can use and contribute back.

**Comment by thraxil** [comment]
archiving repo.
